### ISSUE TITLE
excuse me! Do you have the raw assignment? (unedited ones)

### ISSUE THREAD

**Issue by Josh00-Lu** [zhang-guodong/AI-for-Medicine-Specialization#1]

**Comment by zhang-guodong** [comment]
You can download them from Coursera.
If you need help, please let me know:)

**Comment by Josh00-Lu** [comment]
> You can download them from Coursera.
> If you need help, please let me know:)

Yes... I can't afford the course... I am a college student.

**Comment by zhang-guodong** [comment]
> > You can download them from Coursera.
> > If you need help, please let me know:)
> 
> Yes... I can't afford the course... I am a college student.

Even if I download and give them to you, you cannot run them correctly without other files (like pretrained models).
Maybe you can audit the courses firstly and finish the assignments in a week by "try for free".
Or you can apply for financial aid, which is almost 100% to pass (that is how I enroll the courses).
